[package]
name = "screenhop-core"
version.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true
anyhow.workspace = true
serde.workspace = true
toml.workspace = true
semver.workspace = true
reqwest.workspace = true
tokio.workspace = true
dirs = "6.0"
serde_json = "1.0"
